export const enum DemoPath {
    BrowserSupport = 'documentation/browser-support',
    WhatIsMaskito = 'getting-started/what-is-maskito',
    MaskitoLibraries = 'getting-started/maskito-libraries',
    CoreConceptsOverview = 'core-concepts/overview',
    MaskExpression = 'core-concepts/mask-expression',
    Processors = 'core-concepts/processors',
    OverwriteMode = 'core-concepts/overwrite-mode',
    Number = 'kit/number',
    Time = 'kit/time',
    Date = 'kit/date',
    DateRange = 'kit/date-range',
    Card = 'recipes/card',
    Phone = 'recipes/phone',
    Sandbox = 'sandbox',
}
