export const enum DemoPath {
    WhatIsMaskito = 'getting-started/what-is-maskito',
    MaskitoLibraries = 'getting-started/maskito-libraries',
    CoreConceptsOverview = 'core-concepts/overview',
    MaskExpression = 'core-concepts/mask-expression',
    ElementState = 'core-concepts/element-state',
    Processors = 'core-concepts/processors',
    OverwriteMode = 'core-concepts/overwrite-mode',
    Transformer = 'core-concepts/transformer',
    Number = 'kit/number',
    Time = 'kit/time',
    Date = 'kit/date',
    DateRange = 'kit/date-range',
    DateTime = 'kit/date-time',
    Card = 'recipes/card',
    Phone = 'recipes/phone',
    Prefix = 'recipes/prefix',
    Postfix = 'recipes/postfix',
    Textarea = 'recipes/textarea',
    Angular = 'angular',
    BrowserSupport = 'browser-support',
    Changelog = 'changelog',
    Stackblitz = 'stackblitz',
    Cypress = 'cypress',
}
