name: Action for global variables
description: CI variables

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "Provide global variables ..."

        export IS_MAIN_BRANCH="${{ github.ref == 'refs/heads/main' }}"
        export IS_FORK="${{ github.event.pull_request.head.repo.full_name != github.repository }}"
        export IS_DEPENDABOT="${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}"

        if [[ "$IS_FORK" == "false" && "$IS_DEPENDABOT" == "false" && "$IS_MAIN_BRANCH" == "false" ]]; then
            export SUPPORT_AUTO_PUSH="true"
        else
            export SUPPORT_AUTO_PUSH="false"
        fi

        echo "IS_MAIN_BRANCH=$IS_MAIN_BRANCH" >> $GITHUB_ENV
        echo "IS_FORK=$IS_FORK" >> $GITHUB_ENV
        echo "IS_DEPENDABOT=$IS_DEPENDABOT" >> $GITHUB_ENV
        echo "SUPPORT_AUTO_PUSH=$SUPPORT_AUTO_PUSH" >> $GITHUB_ENV
