name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug in the Maskito
labels: ['bug']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which package(s) are the source of the bug?
      options:
        - '@maskito/core'
        - '@maskito/kit'
        - '@maskito/angular'
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Please provide a link to a minimal reproduction of the bug
      value: https://tinkoff.github.io/maskito/stackblitz

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
    validations:
      required: true

  - type: input
    id: maskito-version
    attributes:
      label: Maskito version
      placeholder: x.y.z
    validations:
      required: true

  - type: checkboxes
    id: browser-specific
    attributes:
      label: Which browsers have you used?
      description: You may select more than one.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
