name: '🗂 - Engineering Task'
title: '🗂 - '
description: Define or track an engineering task
labels: ['state: needs triage']

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Provide any additional details here as needed.
    validations:
      required: true
