name: Auto-push action
description: Auto-push action

inputs:
  message:
    description: commit message
    required: false
    default: apply changes after linting

runs:
  using: composite
  steps:
    - name: Git status
      shell: bash
      run: |
        git add .
        git status

    - name: Push
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: 'tinkoff-bot'
        commit_user_email: 'tinkoff-bot@users.noreply.github.com'
        commit_author: 'tinkoff-bot <tinkoff-bot@users.noreply.github.com>'
        commit_message: 'chore: ${{ inputs.message }} [tinkoff-bot]'
        status_options: '--untracked-files=no'
        commit_options: '--no-verify'
        skip_fetch: true
