name: 🤖 Auto move new issues into Triage
on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/project@v1.44.2
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}
