name: 🤖 Auto cleanup caches
on:
  push:
    branches: [main]
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: taiga-family/ci/actions/cleanup-cache@1.12.0
        if: github.event_name == 'push'
        with:
          branch-name: ${{ github.head_ref || github.ref_name }}
      - uses: taiga-family/ci/actions/cleanup-cache@1.12.0
        if: github.event_name == 'pull_request'
        with:
          branch-name: refs/pull/${{ github.event.pull_request.number }}/merge
