name: 🤖 Auto dependency review
on:
  pull_request:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: taiga-family/ci/actions/security/dependency-review@1.20.0
