name: 🤖 Auto dependency review
on:
  pull_request:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: taiga-family/ci/actions/dependency-review@1.12.4
