name: 🤖 Auto dependency review
on:
  pull_request:
permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.44.4
      - uses: taiga-family/ci/actions/security/dependency-review@v1.44.4
