name: 🤖 Auto approve by bot
on: pull_request

jobs:
  automated-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: taiga-family/ci/actions/variables@1.12.2
      - uses: taiga-family/ci/actions/two-approve@1.12.2
        if: env.TAIGA_FAMILY_BOT_IS_AUTHOR == 'true'
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
