name: 🤖 Auto approve validation
on: pull_request

env:
  PR_JOBS_NAME: '[ "Packages", "Demo", "Firebase", "Lint result", "tests", "E2E result" ]'
  RELEASE_JOBS_NAME: '[ "Publish" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.27.1
      - uses: taiga-family/ci/actions/setup/variables@v1.27.1
      - id: matrix
        if: env.TAIGA_FAMILY_BOT_IS_AUTHOR == 'true'
        run: |
          if [[ "${{ env.IS_RELEASE_BRANCH }}" == "false" ]]; then
              echo "value=$PR_JOBS_NAME" >> $GITHUB_OUTPUT
          else
            echo "value=$RELEASE_JOBS_NAME" >> $GITHUB_OUTPUT
          fi

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@v1.27.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.27.1
      - uses: taiga-family/ci/actions/setup/variables@v1.27.1
      - uses: taiga-family/ci/actions/auto/approve/double@v1.27.1
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@v1.27.1
        if: env.IS_RELEASE_BRANCH == 'false'
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: auto-approve-${{ github.head_ref }}
  cancel-in-progress: true
