name: 🤖 Auto approve validation
on: pull_request

env:
  PR_JOBS_NAME: '[ "Packages", "Demo", "Firebase", "Lint result", "tests", "E2E result" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.84.0
      - uses: taiga-family/ci/actions/setup/variables@v1.84.0
      - id: matrix
        run: echo "value=$PR_JOBS_NAME" >> $GITHUB_OUTPUT

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@v1.84.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: taiga-family/ci/actions/setup/checkout@v1.84.0
      - uses: taiga-family/ci/actions/setup/variables@v1.84.0
      - uses: taiga-family/ci/actions/auto/approve/double@v1.84.0
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@v1.84.0
        if: ${{ env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true' }}
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: auto-approve-${{ github.head_ref }}
  cancel-in-progress: true
