name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, 'chore(release)') }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
      - uses: taiga-family/actions/setup-node@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
      - run: npx nx build-gh-pages
      - uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: dist/demo/browser
          silent: false
          clean: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
