name: Deploy / preview

on: pull_request

jobs:
  build_and_preview:
    name: Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@916a39693b6360c08dcdd5e91d1d8fef9d40fb64 # v2.6.0
      - uses: taiga-family/actions/setup-node@916a39693b6360c08dcdd5e91d1d8fef9d40fb64 # v2.6.0
      - run: npx nx run-many --target build --all --exclude=demo
      - run: npx nx run demo:build:typecheck

      - name: Debug output
        run: tree dist/demo/browser -P '*.html'

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7 # https://github.com/FirebaseExtended/action-hosting-deploy/issues/440
        if: env.IS_OWNER_MODE == 'true'
        with:
          node-version: 24.18 # https://github.com/firebase/firebase-tools/issues/10726

      - name: Deploy preview
        uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0.11.0
        if: env.IS_OWNER_MODE == 'true'
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MASKITO }}
          projectId: maskito
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
