name: Lint
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/node@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - run: echo "$(git log -1 --pretty=format:"%s")" | npx commitlint --verbose
        if: github.event_name == 'pull_request'

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - uses: taiga-family/ci/actions/setup/node@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - run: npm run typecheck

  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - uses: taiga-family/ci/actions/setup/node@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - run: npm run cspell -- --no-progress

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - uses: taiga-family/ci/actions/setup/node@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - run: npm run prettier ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --write' || '-- --check' }}
      - uses: taiga-family/ci/actions/auto/push@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - uses: taiga-family/ci/actions/setup/node@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - run: npm run stylelint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - uses: taiga-family/ci/actions/auto/push@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: taiga-family/ci/actions/setup/variables@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - uses: taiga-family/ci/actions/setup/node@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
      - run: npm run lint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - uses: taiga-family/ci/actions/auto/push@5762a222cd9305487d147b1bdf6018fc718206bd # v1.219.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  result:
    needs: [commitlint, typecheck, cspell, prettier, stylelint, eslint]
    runs-on: ubuntu-latest
    name: Lint result
    steps:
      - run: echo "Success"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
