name: Lint
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-node@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - run: echo "$(git log -1 --pretty=format:"%s")" | npx commitlint --verbose
        if: github.event_name == 'pull_request'

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - uses: taiga-family/actions/setup-node@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - run: npm run typecheck

  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - uses: taiga-family/actions/setup-node@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - run: npm run cspell -- --no-progress

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-variables@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - uses: taiga-family/actions/setup-node@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - run: npm run prettier ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --write' || '-- --check' }}
      - uses: taiga-family/actions/auto-push@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-variables@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - uses: taiga-family/actions/setup-node@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - run: npm run stylelint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - uses: taiga-family/actions/auto-push@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: taiga-family/actions/setup-variables@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - uses: taiga-family/actions/setup-node@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
      - run: npm run lint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}
      - uses: taiga-family/actions/auto-push@cae818be1384ee5c94f69548d70ab1f50a8e7f01 # v2.2.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  result:
    needs: [commitlint, typecheck, cspell, prettier, stylelint, eslint]
    runs-on: ubuntu-latest
    name: Lint result
    steps:
      - run: echo "Success"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
