name: 🤖 PR suites
on:
  pull_request:
  pull_request_review:
    types: [submitted]

env:
  PR_JOBS_NAME: '[ "Packages", "Demo", "Firebase", "Lint result", "tests", "E2E result" ]'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.87.0
      - id: matrix
        if: env.IS_TAIGA_FAMILY_BOT_PR_AUTHOR == 'true'
        run: echo "value=$PR_JOBS_NAME" >> $GITHUB_OUTPUT

  wait:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        value: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - uses: taiga-family/ci/actions/run/wait-job@v1.87.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: ${{ matrix.value }}

  approve:
    needs: [wait]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.87.0
      - uses: taiga-family/ci/actions/auto/approve/double@v1.87.0
        with:
          token1: ${{ secrets.GITHUB_TOKEN }}
          token2: ${{ secrets.TAIGA_FAMILY_APPROVE_BOT_PAT }}
      - uses: taiga-family/ci/actions/run/merge@v1.87.0
        with:
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    if: github.event.review.state == 'APPROVED'
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.87.0
      - uses: taiga-family/ci/actions/auto/label-when-approved@v1.87.0
        with:
          approvals: 1
          token: ${{ secrets.GITHUB_TOKEN }}

  assign-author:
    name: PR author as an assignee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.87.0
      - uses: toshimaru/auto-author-assign@v2.1.1
        if: env.IS_OWNER_MODE == 'true'
        with:
          repo-token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

concurrency:
  group: pr-suites-${{ github.head_ref }}
  cancel-in-progress: true
