name: ⚠️ Release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - patch
          - minor
          - alpha
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/setup/node@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/run/release-it@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        id: release-it
        with:
          ref: ${{ github.ref }}
          mode: ${{ github.event.inputs.mode }}
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/run/read-package-json@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        id: info

      - name: Announce to Telegram
        if: steps.release-it.outputs.released == 'true'
        uses: taiga-family/ci/actions/messenger/telegram/announce@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        with:
          chatId: ${{ secrets.TAIGA_TELEGRAM_CHAT_ID }}
          topicId: ${{ secrets.TAIGA_TELEGRAM_CHAT_THREAD_ID }}
          token: ${{ secrets.TAIGA_TELEGRAM_BOT_TOKEN }}
          version: v${{ steps.info.outputs.version }}
          textLink: '@maskito/core'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
