name: ⚠️ Release

on:
  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: Bump version as requested
        required: true
        options:
          - patch
          - minor
          - alpha
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
      - uses: taiga-family/actions/setup-node@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
      - uses: taiga-family/actions/release-it@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
        id: release-it
        with:
          ref: ${{ github.ref }}
          mode: ${{ github.event.inputs.mode }}
          npmToken: ${{ secrets.NPM_TOKEN }}
          githubToken: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/actions/read-package-json@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
        id: info

      - name: Announce to Telegram
        if: steps.release-it.outputs.released == 'true'
        uses: taiga-family/actions/messenger-telegram-announce@2446a1d329acc075f7264292facddf0b0c992b53 # v2.1.0
        with:
          chatId: ${{ secrets.TAIGA_TELEGRAM_CHAT_ID }}
          topicId: ${{ secrets.TAIGA_TELEGRAM_CHAT_THREAD_ID }}
          token: ${{ secrets.TAIGA_TELEGRAM_BOT_TOKEN }}
          version: v${{ steps.info.outputs.version }}
          textLink: '@maskito/core'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
